/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description What this server is, in enough detail to explain "nothing is working".
         *
         *     Deliberately no filesystem path: the data directory is an absolute home
         *     path, which is a finding everywhere else in this codebase.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/allowance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Allowance */
        get: operations["get_allowance_api_v1_allowance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Integration Catalog
         * @description Company-independent, so the marketing site can render it too.
         */
        get: operations["integration_catalog_api_v1_integrations_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Integrations */
        get: operations["list_integrations_api_v1_companies__cid__integrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/integrations/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect Integration */
        post: operations["connect_integration_api_v1_companies__cid__integrations__provider__post"];
        /** Disconnect Integration */
        delete: operations["disconnect_integration_api_v1_companies__cid__integrations__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/integrations/{provider}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Integration */
        post: operations["verify_integration_api_v1_companies__cid__integrations__provider__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resources */
        get: operations["list_resources_api_v1_companies__cid__resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Brains
         * @description The providers we know, and the models known to work a shift.
         */
        get: operations["list_brains_api_v1_brains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/brain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brain */
        get: operations["get_brain_api_v1_companies__cid__brain_get"];
        /** Set Brain */
        put: operations["set_brain_api_v1_companies__cid__brain_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/spend-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spend Policy */
        get: operations["get_spend_policy_api_v1_companies__cid__spend_policy_get"];
        /** Set Spend Policy */
        put: operations["set_spend_policy_api_v1_companies__cid__spend_policy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_v1_companies_get"];
        put?: never;
        /** Create Company */
        post: operations["create_company_api_v1_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_v1_companies__cid__get"];
        put?: never;
        post?: never;
        /** Archive Company */
        delete: operations["archive_company_api_v1_companies__cid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/charter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Charter */
        patch: operations["update_charter_api_v1_companies__cid__charter_patch"];
        trace?: never;
    };
    "/api/v1/companies/{cid}/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shifts */
        get: operations["list_shifts_api_v1_companies__cid__shifts_get"];
        put?: never;
        /** Start Shift */
        post: operations["start_shift_api_v1_companies__cid__shifts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shifts/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shift */
        get: operations["get_shift_api_v1_shifts__sid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shifts/{sid}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Shift */
        post: operations["stop_shift_api_v1_shifts__sid__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_companies__cid__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_api_v1_companies__cid__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{aid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_v1_artifacts__aid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{aid}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Artifact */
        get: operations["read_artifact_api_v1_artifacts__aid__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_api_v1_companies__cid__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/objections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Objections */
        get: operations["list_objections_api_v1_companies__cid__objections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attention */
        get: operations["list_attention_api_v1_companies__cid__attention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ledger */
        get: operations["list_ledger_api_v1_companies__cid__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/attention/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Attention */
        post: operations["answer_attention_api_v1_companies__cid__attention__request_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Note */
        post: operations["send_note_api_v1_companies__cid__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Budget Cap */
        put: operations["set_budget_cap_api_v1_companies__cid__budget_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/halt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Halt
         * @description The kill switch. Big red button in the UI, not buried in settings.
         */
        post: operations["halt_api_v1_companies__cid__halt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_companies__cid__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/vault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vault */
        get: operations["list_vault_api_v1_companies__cid__vault_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/vault/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Vault
         * @description Write-only from the user's side: the value goes in once and is never
         *     echoed back by any endpoint.
         */
        put: operations["set_vault_api_v1_companies__cid__vault__name__put"];
        post?: never;
        /** Delete Vault */
        delete: operations["delete_vault_api_v1_companies__cid__vault__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_v1_companies__cid__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read File */
        get: operations["read_file_api_v1_companies__cid__files_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/site/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Site File
         * @description The preview the Website tab iframes. Serves only ``workspace/site/``.
         */
        get: operations["read_site_file_api_v1_companies__cid__site__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_companies__cid__share_post"];
        /** Unpublish */
        delete: operations["unpublish_api_v1_companies__cid__share_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cid}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Cold-load path. A shift must be fully reconstructible from REST alone,
         *     with no live socket — that is what makes "leave and come back" work.
         */
        get: operations["list_events_api_v1_companies__cid__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Snapshot */
        get: operations["public_snapshot_public__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Allowance
         * @description What the studio shows, and what the start button obeys.
         */
        Allowance: {
            /** Plan */
            plan: string;
            /** Label */
            label: string;
            /** Shifts Left */
            shifts_left: number | null;
            /** Shifts Used */
            shifts_used: number;
            /** Grant */
            grant: number | null;
            /** Refill */
            refill: number;
            /** Refill Days */
            refill_days: number;
            /** Next Refill At */
            next_refill_at: string | null;
            /** Byok */
            byok: boolean;
            /** Model Choice */
            model_choice: boolean;
            /** Autonomy */
            autonomy: ("full_auto" | "semi_auto" | "balanced" | "limited" | "full_control")[];
            /** Integrations */
            integrations: string[];
            /** External Spend */
            external_spend: boolean;
        };
        /** AnswerBody */
        AnswerBody: {
            /** Answer */
            answer: string;
        };
        /**
         * Artifact
         * @description A deliverable.
         *
         *     ``confidence`` and ``sources`` are in the contract from day 1 and are the
         *     anti-slop hook: a non-technical founder cannot tell an invented TAM from a
         *     researched one, so the provenance has to be structural, not a prompt request.
         */
        Artifact: {
            /** Id */
            id: string;
            /** Company Id */
            company_id: string;
            kind: components["schemas"]["ArtifactKind"];
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Path */
            path: string;
            /**
             * Mime
             * @default text/markdown
             */
            mime: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Supersedes */
            supersedes?: string | null;
            /** Produced By */
            produced_by: string;
            /** Produced In Shift */
            produced_in_shift: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "sourced" | "inferred" | "assumption";
            /** Sources */
            sources?: string[];
            /**
             * Public
             * @default false
             */
            public: boolean;
            /** Preview Url */
            preview_url?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ArtifactKind
         * @enum {string}
         */
        ArtifactKind: "doc" | "table" | "image" | "site" | "dataset";
        /**
         * AttentionRequest
         * @description The one user-blocking mechanism. Everything else runs unattended.
         */
        AttentionRequest: {
            /** Id */
            id: string;
            /** Company Id */
            company_id: string;
            /** Shift Id */
            shift_id?: string | null;
            /** Role Id */
            role_id?: string | null;
            /** Question */
            question: string;
            /** Options */
            options?: string[];
            /**
             * Asked At
             * Format: date-time
             */
            asked_at: string;
            /** Answered At */
            answered_at?: string | null;
            /** Answer */
            answer?: string | null;
        };
        /**
         * Availability
         * @enum {string}
         */
        Availability: "available" | "beta" | "manual_setup";
        /** BrainBody */
        BrainBody: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Key */
            key: string;
            /** Base Url */
            base_url?: string | null;
        };
        /**
         * BrainChoice
         * @description What a company is currently thinking with. Never the key itself.
         */
        BrainChoice: {
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Key Hint */
            key_hint?: string | null;
            /**
             * Configured
             * @default false
             */
            configured: boolean;
            /**
             * Editable
             * @default true
             */
            editable: boolean;
            /** Note */
            note?: string | null;
        };
        /**
         * BrainProvider
         * @description One place a model can be reached.
         */
        BrainProvider: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Key Name */
            key_name: string;
            /**
             * Models
             * @default []
             */
            models: string[];
            /**
             * Avoid
             * @default {}
             */
            avoid: {
                [key: string]: string;
            };
            /**
             * Free Note
             * @default
             */
            free_note: string;
            /**
             * Console Url
             * @default
             */
            console_url: string;
            /**
             * Key Hint
             * @default
             */
            key_hint: string;
            /**
             * Openai Compatible
             * @default true
             */
            openai_compatible: boolean;
            /**
             * Needs Base Url
             * @default false
             */
            needs_base_url: boolean;
            /**
             * Probe Url
             * @default
             */
            probe_url: string;
        };
        /** Budget */
        Budget: {
            /** Spent */
            spent: string;
            /** Cap */
            cap: string;
            /** Per Shift Cap */
            per_shift_cap: string;
            /**
             * Currency
             * @default USD
             * @constant
             */
            currency: "USD";
        };
        /** BudgetBody */
        BudgetBody: {
            /** Cap */
            cap: number | string;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "database" | "payments" | "hosting" | "email";
        /**
         * Charter
         * @description What the company is for.
         *
         *     Structured rather than a blob: the gap between what a non-technical user types
         *     (two sentences) and what the roles need is the real UX problem, and a guided
         *     capture flow needs somewhere to put its answers.
         */
        Charter: {
            /** Idea */
            idea: string;
            /** One Liner */
            one_liner: string;
            /** Audience */
            audience: string;
            /** Success Looks Like */
            success_looks_like: string;
            /** Constraints */
            constraints?: string[];
            /** Tone */
            tone?: string | null;
            /**
             * Autonomy
             * @default balanced
             * @enum {string}
             */
            autonomy: "full_auto" | "semi_auto" | "balanced" | "limited" | "full_control";
        };
        /**
         * CharterPatch
         * @description Partial charter update. Not frozen — it is a request body.
         */
        CharterPatch: {
            /** One Liner */
            one_liner?: string | null;
            /** Audience */
            audience?: string | null;
            /** Success Looks Like */
            success_looks_like?: string | null;
            /** Constraints */
            constraints?: string[] | null;
            /** Tone */
            tone?: string | null;
            /** Autonomy */
            autonomy?: ("full_auto" | "semi_auto" | "balanced" | "limited" | "full_control") | null;
        };
        /** Company */
        Company: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            status: components["schemas"]["CompanyStatus"];
            charter: components["schemas"]["Charter"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Shift Count
             * @default 0
             */
            shift_count: number;
            progress: components["schemas"]["Progress"];
            budget: components["schemas"]["Budget"];
            /** Roster */
            roster?: components["schemas"]["Role"][];
            share?: components["schemas"]["ShareLink"] | null;
        };
        /**
         * CompanyStatus
         * @enum {string}
         */
        CompanyStatus: "draft" | "idle" | "working" | "blocked" | "halted" | "archived";
        /** ConnectBody */
        ConnectBody: {
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * Connection
         * @description Derived at read time from the vault, the log, and the plan.
         */
        Connection: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "supabase" | "stripe" | "netlify" | "resend" | "x402" | "moonpay";
            status: components["schemas"]["ConnectionStatus"];
            /** Fields Present */
            fields_present?: string[];
            /** Hints */
            hints?: {
                [key: string]: string;
            };
            /** Connected At */
            connected_at?: string | null;
            /** Verified At */
            verified_at?: string | null;
            /** Message */
            message?: string | null;
            /** Scope Note */
            scope_note?: string | null;
            /** Blocks */
            blocks?: string[];
            /** Unavailable Reason */
            unavailable_reason?: string | null;
        };
        /**
         * ConnectionStatus
         * @enum {string}
         */
        ConnectionStatus: "not_connected" | "connected" | "needs_attention" | "unavailable";
        /** CreateCompanyBody */
        CreateCompanyBody: {
            /** Idea */
            idea: string;
            /** Name */
            name?: string | null;
        };
        /**
         * CredentialClass
         * @enum {string}
         */
        CredentialClass: "public" | "secret" | "reference";
        /**
         * CredentialField
         * @description One value the founder pastes in, or the team discovers later.
         */
        CredentialField: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            kind: components["schemas"]["CredentialClass"];
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Pattern */
            pattern?: string | null;
            /**
             * Help
             * @default
             */
            help: string;
            /**
             * Secret Input
             * @default true
             */
            secret_input: boolean;
            /**
             * Team Fills It
             * @default false
             */
            team_fills_it: boolean;
        };
        /** Decision */
        Decision: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Rationale */
            rationale: string;
            /** Alternatives Rejected */
            alternatives_rejected?: string[];
            /** Made By */
            made_by: string;
            /** Made In Shift */
            made_in_shift: string;
            /** Contested By */
            contested_by?: string | null;
            /** Contest Note */
            contest_note?: string | null;
            /**
             * Reversible
             * @default true
             */
            reversible: boolean;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntegrationSpec
         * @description A service, described in the founder's terms rather than the vendor's.
         */
        IntegrationSpec: {
            /**
             * Id
             * @enum {string}
             */
            id: "supabase" | "stripe" | "netlify" | "resend" | "x402" | "moonpay";
            /** Display Name */
            display_name: string;
            category: components["schemas"]["Category"];
            /** @default available */
            availability: components["schemas"]["Availability"];
            /** What It Does */
            what_it_does: string;
            /** Unlocks */
            unlocks?: string[];
            /** Employees */
            employees?: string[];
            /**
             * Cost Note
             * @default
             */
            cost_note: string;
            /**
             * Minutes
             * @default 5
             */
            minutes: number;
            /** Fields */
            fields?: components["schemas"]["CredentialField"][];
            /** Refuses */
            refuses?: string[];
            /** Steps */
            steps?: components["schemas"]["WalkStep"][];
            /**
             * Verify Label
             * @default Check it works
             */
            verify_label: string;
            /** Docs Url */
            docs_url?: string | null;
            /** Manual Note */
            manual_note?: string | null;
        };
        /**
         * IntegrationState
         * @description Spec and connection together: one payload the page can render whole.
         */
        IntegrationState: {
            spec: components["schemas"]["IntegrationSpec"];
            connection: components["schemas"]["Connection"];
        };
        /** LedgerEntry */
        LedgerEntry: {
            /** Id */
            id: string;
            /** Company Id */
            company_id: string;
            /** Shift Id */
            shift_id?: string | null;
            /** Role Id */
            role_id?: string | null;
            /** Amount */
            amount: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "llm" | "tool" | "adjustment";
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** NoteBody */
        NoteBody: {
            /** Text */
            text: string;
        };
        /**
         * Objection
         * @description The critic's output — a first-class resource, not a log line.
         *
         *     A non-technical founder cannot evaluate whether an artifact is any good. What
         *     they *can* evaluate is a specific, falsifiable objection naming a specific
         *     claim and what evidence would settle it. This is the primary defence against
         *     plausible slop, so it gets its own list endpoint and equal billing in the UI.
         */
        Objection: {
            /** Id */
            id: string;
            /** Company Id */
            company_id: string;
            /** Shift Id */
            shift_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "fatal" | "serious" | "noted";
            /** Text */
            text: string;
            /** About */
            about?: string | null;
            /** About Label */
            about_label?: string | null;
            /**
             * Settled By
             * @default
             */
            settled_by: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /**
         * Progress
         * @description User-facing progress. The raw judge score never leaves the engine.
         */
        Progress: {
            /** Percent */
            percent: number;
            /** Headline */
            headline: string;
            /** Whats Missing */
            whats_missing?: string[];
            /** Judged At */
            judged_at?: string | null;
        };
        /**
         * ProvisionedResource
         * @description Something the team made that the founder now owns.
         *
         *     Recorded so the studio can show a real address instead of a placeholder,
         *     and so a second shift knows the first one already built this.
         */
        ProvisionedResource: {
            /** Id */
            id: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "supabase" | "stripe" | "netlify" | "resend" | "x402" | "moonpay";
            /**
             * Kind
             * @enum {string}
             */
            kind: "project" | "site" | "deployment" | "function" | "bucket" | "payment_link";
            /** Ref */
            ref: string;
            /** Label */
            label: string;
            /** Url */
            url?: string | null;
            /** Created In Shift */
            created_in_shift?: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** PublicSnapshot */
        PublicSnapshot: {
            /** Company Name */
            company_name: string;
            /** One Liner */
            one_liner: string;
            progress: components["schemas"]["Progress"];
            /** Roster */
            roster: components["schemas"]["Role"][];
            /** Shifts */
            shifts?: components["schemas"]["Shift"][];
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            /** Decisions */
            decisions?: components["schemas"]["Decision"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /**
         * Role
         * @description An employee, as the user understands them. Never called an "agent" in the UI.
         */
        Role: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Job Title */
            job_title: string;
            /** Avatar */
            avatar: string;
            /** Accent */
            accent: string;
            /** Blurb */
            blurb: string;
            /** @default idle */
            status: components["schemas"]["RoleStatus"];
            /** Current Activity */
            current_activity?: string | null;
            /**
             * Shifts Worked
             * @default 0
             */
            shifts_worked: number;
        };
        /**
         * RoleStatus
         * @enum {string}
         */
        RoleStatus: "idle" | "working" | "blocked" | "done" | "failed";
        /** ShareLink */
        ShareLink: {
            /** Token */
            token: string;
            /** Url */
            url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Revoked At */
            revoked_at?: string | null;
            /**
             * Include Shifts
             * @default true
             */
            include_shifts: boolean;
            /**
             * Include Artifacts
             * @default true
             */
            include_artifacts: boolean;
            /** Scanned Clean At */
            scanned_clean_at?: string | null;
        };
        /** ShareOptions */
        ShareOptions: {
            /**
             * Include Shifts
             * @default true
             */
            include_shifts: boolean;
            /**
             * Include Artifacts
             * @default true
             */
            include_artifacts: boolean;
        };
        /** Shift */
        Shift: {
            /** Id */
            id: string;
            /** Company Id */
            company_id: string;
            /** Number */
            number: number;
            status: components["schemas"]["ShiftStatus"];
            phase?: components["schemas"]["ShiftPhase"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Agenda */
            agenda?: string[];
            /** Summary */
            summary?: string | null;
            /** Artifacts Produced */
            artifacts_produced?: string[];
            /** Decisions Made */
            decisions_made?: string[];
            /**
             * Cost
             * @default 0
             */
            cost: string;
            /** Roles Active */
            roles_active?: string[];
            /** Failure Reason */
            failure_reason?: string | null;
        };
        /** ShiftEvent */
        ShiftEvent: {
            /** Seq */
            seq: number;
            /** Id */
            id: string;
            /** Company Id */
            company_id: string;
            /** Shift Id */
            shift_id?: string | null;
            /** Role Id */
            role_id?: string | null;
            kind: components["schemas"]["ShiftEventKind"];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Text */
            text: string;
            /** Detail */
            detail?: string | null;
            /** Icon */
            icon?: string | null;
            /** Ref */
            ref?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * ShiftEventKind
         * @enum {string}
         */
        ShiftEventKind: "shift.started" | "shift.phase" | "shift.completed" | "shift.failed" | "role.started" | "role.activity" | "role.said" | "role.finished" | "role.failed" | "artifact.created" | "artifact.updated" | "decision.made" | "decision.contested" | "task.added" | "task.claimed" | "task.done" | "budget.spent" | "budget.exceeded" | "progress.updated" | "attention.needed" | "heartbeat";
        /**
         * ShiftPhase
         * @enum {string}
         */
        ShiftPhase: "planning" | "working" | "review" | "integrating" | "closing";
        /**
         * ShiftStatus
         * @enum {string}
         */
        ShiftStatus: "queued" | "running" | "completed" | "failed" | "aborted" | "budget_exceeded";
        /**
         * SpendPolicy
         * @description What the team may spend on *services*, as distinct from thinking.
         *
         *     Separate from the budget because it is a different kind of money: the LLM
         *     bill is ours to meter, a Supabase project on a paid tier is a recurring
         *     charge on the founder's own card. Everything here is off by default —
         *     Supabase, Netlify and Resend all have free tiers a whole product fits in.
         */
        "SpendPolicy-Input": {
            /**
             * External Cap
             * @default 0.00
             */
            external_cap: number | string;
            /**
             * Allow Paid Signup
             * @default false
             */
            allow_paid_signup: boolean;
            /**
             * X402 Per Call Cap
             * @default 0.10
             */
            x402_per_call_cap: number | string;
            /**
             * X402 Shift Cap
             * @default 1.00
             */
            x402_shift_cap: number | string;
            /**
             * Allow X402
             * @default false
             */
            allow_x402: boolean;
            /**
             * Stripe Mode
             * @default test
             * @enum {string}
             */
            stripe_mode: "test" | "live";
        };
        /**
         * SpendPolicy
         * @description What the team may spend on *services*, as distinct from thinking.
         *
         *     Separate from the budget because it is a different kind of money: the LLM
         *     bill is ours to meter, a Supabase project on a paid tier is a recurring
         *     charge on the founder's own card. Everything here is off by default —
         *     Supabase, Netlify and Resend all have free tiers a whole product fits in.
         */
        "SpendPolicy-Output": {
            /**
             * External Cap
             * @default 0.00
             */
            external_cap: string;
            /**
             * Allow Paid Signup
             * @default false
             */
            allow_paid_signup: boolean;
            /**
             * X402 Per Call Cap
             * @default 0.10
             */
            x402_per_call_cap: string;
            /**
             * X402 Shift Cap
             * @default 1.00
             */
            x402_shift_cap: string;
            /**
             * Allow X402
             * @default false
             */
            allow_x402: boolean;
            /**
             * Stripe Mode
             * @default test
             * @enum {string}
             */
            stripe_mode: "test" | "live";
        };
        /** StartShiftBody */
        StartShiftBody: {
            /** Focus */
            focus?: string | null;
        };
        /** StopShiftBody */
        StopShiftBody: {
            /**
             * Reason
             * @default user
             */
            reason: string;
        };
        /** Task */
        Task: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** @default open */
            status: components["schemas"]["TaskStatus"];
            /** Owner */
            owner?: string | null;
            /** Claimed By Shift */
            claimed_by_shift?: string | null;
            /**
             * Priority
             * @default 3
             */
            priority: number;
            /** Depends On */
            depends_on?: string[];
            /** Created In Shift */
            created_in_shift?: string | null;
            /** Closed In Shift */
            closed_in_shift?: string | null;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "open" | "claimed" | "done" | "dropped" | "blocked";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VaultItem
         * @description A key the company keeps for its work — an API key, an env var, a password.
         *
         *     The value never appears in this model, in any API response, in the event log,
         *     or on a share page. ``hint`` is the only echo the user ever gets, and it is
         *     enough to tell two keys apart without being enough to use one.
         */
        VaultItem: {
            /** Name */
            name: string;
            /** Hint */
            hint: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** VaultValueBody */
        VaultValueBody: {
            /** Value */
            value: string;
        };
        /**
         * WalkStep
         * @description One step of the guided walkthrough.
         *
         *     Prose only, never a command. Each step must stand on its own words: the
         *     picture is an illustration, not the instruction, so a walkthrough with no
         *     pictures yet is still followable. Enforced by a test.
         */
        WalkStep: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Link */
            link?: string | null;
            /** Link Label */
            link_label?: string | null;
            /** Media */
            media?: string | null;
            /** Media Alt */
            media_alt?: string | null;
            /** Field */
            field?: string | null;
            /** Warning */
            warning?: string | null;
        };
        /**
         * WorkspaceFile
         * @description One file the team wrote while building. Path is workspace-relative;
         *     nothing outside ``workspace/`` is ever enumerated.
         */
        WorkspaceFile: {
            /** Path */
            path: string;
            /** Size */
            size: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "binary";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_allowance_api_v1_allowance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allowance"];
                };
            };
        };
    };
    integration_catalog_api_v1_integrations_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationSpec"][];
                };
            };
        };
    };
    list_integrations_api_v1_companies__cid__integrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationState"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_integration_api_v1_companies__cid__integrations__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_integration_api_v1_companies__cid__integrations__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_integration_api_v1_companies__cid__integrations__provider__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resources_api_v1_companies__cid__resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionedResource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brains_api_v1_brains_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainProvider"][];
                };
            };
        };
    };
    get_brain_api_v1_companies__cid__brain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainChoice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_brain_api_v1_companies__cid__brain_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrainBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainChoice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spend_policy_api_v1_companies__cid__spend_policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendPolicy-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_spend_policy_api_v1_companies__cid__spend_policy_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpendPolicy-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendPolicy-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_v1_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"][];
                };
            };
        };
    };
    create_company_api_v1_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_companies__cid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_company_api_v1_companies__cid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_charter_api_v1_companies__cid__charter_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharterPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shifts_api_v1_companies__cid__shifts_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: number | null;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_shift_api_v1_companies__cid__shifts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartShiftBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shift_api_v1_shifts__sid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_shift_api_v1_shifts__sid__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopShiftBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_companies__cid__tasks_get: {
        parameters: {
            query?: {
                task_status?: components["schemas"]["TaskStatus"] | null;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_companies__cid__artifacts_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ArtifactKind"] | null;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__aid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_artifact_api_v1_artifacts__aid__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_api_v1_companies__cid__decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_objections_api_v1_companies__cid__objections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Objection"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attention_api_v1_companies__cid__attention_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionRequest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ledger_api_v1_companies__cid__ledger_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_attention_api_v1_companies__cid__attention__request_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_note_api_v1_companies__cid__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_budget_cap_api_v1_companies__cid__budget_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    halt_api_v1_companies__cid__halt_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_v1_companies__cid__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vault_api_v1_companies__cid__vault_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaultItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_vault_api_v1_companies__cid__vault__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VaultValueBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaultItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vault_api_v1_companies__cid__vault__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_v1_companies__cid__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceFile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_file_api_v1_companies__cid__files_content_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_site_file_api_v1_companies__cid__site__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_companies__cid__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareOptions"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpublish_api_v1_companies__cid__share_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_companies__cid__events_get: {
        parameters: {
            query?: {
                since_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_snapshot_public__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
